version: '3'

services:

  php:
#    build:
#      context: ./Php
    image: 18736050080/myphp_new
    container_name: php-fpm
    restart: always
    ports:
      - "${HTTP_SWOOLE_PORT}:9572"
      - "3333:9582"
      - "4444:9592"
    volumes:
      - ${WORK_DIR}:/data/www
      - ${PHP_LOG_DIR}:/var/opt/remi/php73/log
    working_dir: /data/www
    expose:
      - 9000
      - 9572
      - 9582
      - 9592
    networks:
      - nginx-php

  go:
    image: 18736050080/go
    container_name: mygo
    restart: always
    ports:
      - "9888:9888"
      - "22:22"
    volumes:
      - ${GOPATH}:/home/golang
    working_dir: /home/golang
    expose:
      - 9888
      - 22
    networks:
      - nginx-go

  nginx:
    image: nginx
    container_name: ng
    restart: always
    depends_on:
      - php
      - go
    volumes:
      - ${WORK_DIR}:/data/www
      - ${NGINX_LOG_DIR}:/var/logs
      - ${NGINX_CONF_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_DIR}/conf.d:/etc/nginx/conf.d
    working_dir: /data/www
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    expose:
      - 443
      - 80
    networks:
      - nginx-php
      - nginx-go

networks:
  nginx-php:
    driver: bridge
  nginx-go:
    driver: bridge