version: '3'

services:

  redis:
    image : redis:5.0
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DOCKER_ENV}${REDIS_CONF}:/usr/local/etc/redis/redis.conf
      - ${DOCKER_ENV}${REDIS_DATA}:/data
      - ${DOCKER_ENV}${REDIS_LOGS}:/var/log/redis.log
    expose:
      - 6379

  php:
#    build:
#      context: ./Php
    image: 18736050080/myphp:v1
    container_name: php
    restart: always
    ports:
      - "${HTTP_SWOOLE_PORT}:9577"
    volumes:
      - ${DOCKER_ENV}${WORK_DIR}:/data/www
      - ${DOCKER_ENV}${PHP_LOG_DIR}:/var/opt/remi/php73/log
    working_dir: /data/www
    expose:
      - 9000
    networks:
      - nginx-php

  go:
#    build:
#      context: ./Go
    image: 18736050080/mygo:v2
    container_name: mygo
    restart: always
    ports:
      - "9888:9888"
      - "9788:9788"
      - "22:22"
    volumes:
      - ${GOPATH}:/home/golang
    working_dir: /home/golang/src
    expose:
      - 9888
      - 22
    networks:
      - nginx-go

  nginx:
    image: nginx
    container_name: ng
    restart: always
    depends_on:
      - php
      - go
    volumes:
      - ${DOCKER_ENV}${WORK_DIR}:/data/www
      - ${DOCKER_ENV}${NGINX_LOG_DIR}:/var/logs
      - ${DOCKER_ENV}${NGINX_CONF_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_ENV}${NGINX_CONF_DIR}/conf.d:/etc/nginx/conf.d
    working_dir: /data/www
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    expose:
      - 443
      - 80
    networks:
      - nginx-php
      - nginx-go

networks:
  nginx-php:
    driver: bridge
  nginx-go:
    driver: bridge