version: '3'

services:

  php:
    build:
      context: ./Php
    image: centos
    container_name: my-php-fpm
    restart: always
    ports:
      - "${HTTP_SWOOLE_PORT}:9572"
    volumes:
      - ${WORK_DIR}:/data/www
    networks:
      - nginx-php
    command: "php-fpm"

networks:
  nginx-php:
    driver: bridge