version: '3'

services:

  php:
    image: php:fpm
    container_name: php-fpm
    restart: always
    ports:
      - "${HTTP_SWOOLE_PORT}:9572"
    volumes:
      - ${WORK_DIR}:/data/www
    working_dir: /data/www
    networks:
      - nginx-php

  nginx:
    image: nginx
    container_name: ng
    restart: on-failure
    depends_on:
      - php
    working_dir: /data/www
    volumes:
      - ${WORK_DIR}:/data/www
      - ${NGINX_LOG_DIR}:/var/logs
      - ${NGINX_CONF_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_DIR}/conf.d:/etc/nginx/conf.d
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    networks:
      - nginx-php

networks:
  nginx-php:
    driver: bridge